INSERT INTO `currencies` VALUES (1, 'Afghanistan', 'Afghan afghani', 'AFN', 'AFN');
INSERT INTO `currencies` VALUES (3, 'Albania', 'Albanian lek', 'ALL', 'ALL');
INSERT INTO `currencies` VALUES (4, 'Algeria', 'Algerian dinar', 'DZD', 'دج');
INSERT INTO `currencies` VALUES (6, 'Angola', 'Angolan kwanza', 'AOA', 'Kz');
INSERT INTO `currencies` VALUES (7, 'Anguilla', 'East Caribbean dollar', 'XCD', 'EC$');
INSERT INTO `currencies` VALUES (9, 'Argentina', 'Argentine peso', 'ARS', 'AR$');
INSERT INTO `currencies` VALUES (10, 'Armenia', 'Armenian dram', 'AMD', 'դր');
INSERT INTO `currencies` VALUES (11, 'Aruba', 'Aruban florin', 'AWG', 'ƒ');
INSERT INTO `currencies` VALUES (12, 'Australia', 'Australian dollar', 'AUD', 'AU$');
INSERT INTO `currencies` VALUES (14, 'Azerbaijan', 'Azerbaijani manat', 'AZN', 'ман');
INSERT INTO `currencies` VALUES (15, 'Bahamas', 'Bahamian dollar', 'BSD', 'BS$');
INSERT INTO `currencies` VALUES (16, 'Bahrain', 'Bahraini dinar', 'BHD', 'ب.د');
INSERT INTO `currencies` VALUES (17, 'Bangladesh', 'Bangladeshi taka', 'BDT', '৳');
INSERT INTO `currencies` VALUES (18, 'Barbados', 'Barbados dollar', 'BBD', 'Bds$');
INSERT INTO `currencies` VALUES (19, 'Belarus', 'Belarusian ruble', 'BYR', 'Br');
INSERT INTO `currencies` VALUES (21, 'Belize', 'Belize dollar', 'BZD', 'BZ$');
INSERT INTO `currencies` VALUES (22, 'Benin', 'CFA franc BCEAO', 'XOF', 'franc');
INSERT INTO `currencies` VALUES (23, 'Bermuda', 'Bermudian dollar', 'BMD', 'BD$');
INSERT INTO `currencies` VALUES (24, 'Bhutan', 'Bhutanese ngultrum', 'BTN', 'Nu');
INSERT INTO `currencies` VALUES (25, 'Bolivia', 'Boliviano', 'BOB', 'Bs');
INSERT INTO `currencies` VALUES (26, 'Bosnia & Herzegovina', 'Bosnia and Herzegovina convertible mark', 'BAM', 'KM');
INSERT INTO `currencies` VALUES (27, 'Botswana', 'Botswana pula', 'BWP', 'P');
INSERT INTO `currencies` VALUES (28, 'Brazil', 'Brazilian real', 'BRL', 'R$');
INSERT INTO `currencies` VALUES (29, 'Brunei', 'Brunei dollar', 'BND', 'B$');
INSERT INTO `currencies` VALUES (30, 'Bulgaria', 'Bulgarian lev', 'BGN', 'лв');
INSERT INTO `currencies` VALUES (32, 'Burundi', 'Burundian franc', 'BIF', 'FBu');
INSERT INTO `currencies` VALUES (33, 'Cambodia', 'Cambodian riel', 'KHR', '៛');
INSERT INTO `currencies` VALUES (34, 'Cameroon', 'CFA franc BEAC', 'XAF', 'franc');
INSERT INTO `currencies` VALUES (35, 'Canada', 'Canadian dollar', 'CAD', 'CA$');
INSERT INTO `currencies` VALUES (36, 'Cape Verde', 'Cape Verde escudo', 'CVE', 'CV$');
INSERT INTO `currencies` VALUES (37, 'Cayman Islands', 'Cayman Islands dollar', 'KYD', 'CI$');
INSERT INTO `currencies` VALUES (40, 'Chile', 'Chilean peso', 'CLP', 'CL$');
INSERT INTO `currencies` VALUES (41, 'China', 'Chinese yuan', 'CNY', 'CN¥');
INSERT INTO `currencies` VALUES (44, 'Colombia', 'Colombian peso', 'COP', 'Col$');
INSERT INTO `currencies` VALUES (45, 'Comoros', 'Comoro franc', 'KMF', 'KMF');
INSERT INTO `currencies` VALUES (49, 'Costa Rica', 'Costa Rican colon', 'CRC', '₡');
INSERT INTO `currencies` VALUES (51, 'Croatia (Hrvatska)', 'Croatian kuna', 'HRK', 'HRK');
INSERT INTO `currencies` VALUES (52, 'Cuba', 'Cuban convertible peso', 'CUC', 'CU$');
INSERT INTO `currencies` VALUES (53, 'Cyprus', 'Cypriot pound', 'CYP', 'CY£');
INSERT INTO `currencies` VALUES (54, 'Czech Republic', 'Czech koruna', 'CZK', 'Kč');
INSERT INTO `currencies` VALUES (55, 'Denmark', 'Danish krone', 'DKK', 'ø');
INSERT INTO `currencies` VALUES (56, 'Djibouti', 'Djiboutian franc', 'DJF', 'Fdj');
INSERT INTO `currencies` VALUES (58, 'Dominican Republic', 'Dominican peso', 'DOP', 'RD$');
INSERT INTO `currencies` VALUES (60, 'Egypt', 'Egyptian pound', 'EGP', 'ج.م');
INSERT INTO `currencies` VALUES (63, 'Eritrea', 'Eritrean nakfa', 'ERN', 'Nfk');
INSERT INTO `currencies` VALUES (64, 'Estonia', 'Estonian kroon', 'EEK', 'KR');
INSERT INTO `currencies` VALUES (65, 'Ethiopia', 'Ethiopian birr', 'ETB', 'Br');
INSERT INTO `currencies` VALUES (67, 'Falkland Islands (Malvinas)', 'Falkland Islands pound', 'FKP', 'FK£');
INSERT INTO `currencies` VALUES (68, 'Fiji', 'Fiji dollar', 'FJD', 'FJ$');
INSERT INTO `currencies` VALUES (70, 'France', 'Euro', 'EUR', '€');
INSERT INTO `currencies` VALUES (72, 'French Polynesia', 'CFP franc (franc Pacifique)', 'XPF', 'CFP');
INSERT INTO `currencies` VALUES (75, 'Gambia', 'Gambian dalasi', 'GMD', 'D');
INSERT INTO `currencies` VALUES (76, 'Georgia', 'Georgian lari', 'GEL', 'GEL');
INSERT INTO `currencies` VALUES (78, 'Ghana', 'Ghanaian cedi', 'GHC', '₵');
INSERT INTO `currencies` VALUES (79, 'Gibraltar', 'Gibraltar pound', 'GIP', 'GI£');
INSERT INTO `currencies` VALUES (85, 'Guatemala', 'Guatemalan quetzal', 'GTQ', 'Q');
INSERT INTO `currencies` VALUES (86, 'Guinea', 'Guinean franc', 'GNF', 'FG');
INSERT INTO `currencies` VALUES (88, 'Guyana', 'Guyanese dollar', 'GYD', 'GY$');
INSERT INTO `currencies` VALUES (89, 'Haiti', 'Haitian gourde', 'HTG', 'G');
INSERT INTO `currencies` VALUES (90, 'Honduras', 'Honduran lempira', 'HNL', 'L');
INSERT INTO `currencies` VALUES (91, 'Hong Kong', 'Hong Kong dollar', 'HKD', 'HK$');
INSERT INTO `currencies` VALUES (92, 'Hungary', 'Hungarian forint', 'HUF', 'Ft');
INSERT INTO `currencies` VALUES (93, 'Iceland', 'Icelandic króna', 'ISK', 'ISK');
INSERT INTO `currencies` VALUES (94, 'India', 'Indian rupee', 'INR', 'IN₨');
INSERT INTO `currencies` VALUES (95, 'Indonesia', 'Indonesian rupiah', 'IDR', 'Rp');
INSERT INTO `currencies` VALUES (96, 'Iran', 'Iranian rial', 'IRR', 'ريال');
INSERT INTO `currencies` VALUES (97, 'Iraq', 'Iraqi dinar', 'IQD', 'ع.د');
INSERT INTO `currencies` VALUES (100, 'Israel', 'Israeli new shekel', 'ILS', '₪');
INSERT INTO `currencies` VALUES (102, 'Jamaica', 'Jamaican dollar', 'JMD', 'JA$');
INSERT INTO `currencies` VALUES (103, 'Japan', 'Japanese yen', 'JPY', 'JP¥');
INSERT INTO `currencies` VALUES (105, 'Jordan', 'Jordanian dinar', 'JOD', 'JD');
INSERT INTO `currencies` VALUES (106, 'Kazakhstan', 'Kazakhstani tenge', 'KZT', 'KZT');
INSERT INTO `currencies` VALUES (107, 'Kenya', 'Kenyan shilling', 'KES', 'KSh');
INSERT INTO `currencies` VALUES (109, 'Korea, North', 'North Korean won', 'KPW', '₩');
INSERT INTO `currencies` VALUES (110, 'Korea, South', 'South Korean won', 'KRW', '₩');
INSERT INTO `currencies` VALUES (111, 'Kuwait', 'Kuwaiti dinar', 'KWD', 'د.ك');
INSERT INTO `currencies` VALUES (112, 'Kyrgyzstan', 'Kyrgyzstani som', 'KGS', 'KGS');
INSERT INTO `currencies` VALUES (113, 'Laos', 'Lao kip', 'LAK', '₭');
INSERT INTO `currencies` VALUES (114, 'Latvia', 'Latvian lats', 'LVL', 'Ls');
INSERT INTO `currencies` VALUES (115, 'Lebanon', 'Lebanese pound', 'LBP', 'ل.ل');
INSERT INTO `currencies` VALUES (116, 'Lesotho', 'Lesotho loti', 'LSL', 'L');
INSERT INTO `currencies` VALUES (117, 'Liberia', 'Liberian dollar', 'LRD', 'L$');
INSERT INTO `currencies` VALUES (118, 'Libya', 'Libyan dinar', 'LYD', 'ل.د');
INSERT INTO `currencies` VALUES (120, 'Lithuania', 'Lithuanian litas', 'LTL', 'Lt');
INSERT INTO `currencies` VALUES (122, 'Macau', 'Macanese pataca', 'MOP', 'MO$');
INSERT INTO `currencies` VALUES (123, 'Macedonia', 'Macedonian denar', 'MKD', 'MKD');
INSERT INTO `currencies` VALUES (124, 'Madagascar', 'Malagasy ariary', 'MGA', 'MGA');
INSERT INTO `currencies` VALUES (125, 'Malawi', 'Malawian kwacha', 'MWK', 'MK');
INSERT INTO `currencies` VALUES (126, 'Malaysia', 'Malaysian ringgit', 'MYR', 'RM');
INSERT INTO `currencies` VALUES (127, 'Maldives', 'Maldivian rufiyaa', 'MVR', 'MRf');
INSERT INTO `currencies` VALUES (129, 'Malta', 'Maltese lira', 'MTL', 'Lm');
INSERT INTO `currencies` VALUES (132, 'Mauritania', 'Mauritanian ouguiya', 'MRO', 'UM');
INSERT INTO `currencies` VALUES (133, 'Mauritius', 'Mauritian rupee', 'MUR', 'MU₨');
INSERT INTO `currencies` VALUES (135, 'Mexico', 'Mexican peso', 'MXN', 'Mex$');
INSERT INTO `currencies` VALUES (137, 'Moldova', 'Moldovan leu', 'MDL', 'MDL');
INSERT INTO `currencies` VALUES (139, 'Mongolia', 'Mongolian tögrög', 'MNT', '₮');
INSERT INTO `currencies` VALUES (142, 'Morocco', 'Moroccan dirham', 'MAD', 'د.م');
INSERT INTO `currencies` VALUES (143, 'Mozambique', 'Mozambican metical', 'MZN', 'MTn');
INSERT INTO `currencies` VALUES (144, 'Myanmar (Burma)', 'Myanmar kyat', 'MMK', 'K');
INSERT INTO `currencies` VALUES (145, 'Namibia', 'Namibian dollar', 'NAD', 'N$');
INSERT INTO `currencies` VALUES (147, 'Nepal', 'Nepalese rupee', 'NPR', 'NP₨');
INSERT INTO `currencies` VALUES (149, 'Netherlands Antilles', 'Netherlands Antillean guilder', 'ANG', 'NAƒ');
INSERT INTO `currencies` VALUES (151, 'New Zealand', 'New Zealand dollar', 'NZD', 'NZ$');
INSERT INTO `currencies` VALUES (152, 'Nicaragua', 'Nicaraguan córdoba', 'NIO', 'C$');
INSERT INTO `currencies` VALUES (154, 'Nigeria', 'Nigerian naira', 'NGN', '₦');
INSERT INTO `currencies` VALUES (158, 'Norway', 'Norwegian krone', 'NOK', 'øre');
INSERT INTO `currencies` VALUES (159, 'Oman', 'Omani rial', 'OMR', 'ر.ع');
INSERT INTO `currencies` VALUES (160, 'Pakistan', 'Pakistani rupee', 'PKR', 'PKRs');
INSERT INTO `currencies` VALUES (163, 'Panama', 'Panamanian balboa', 'PAB', 'PAB');
INSERT INTO `currencies` VALUES (164, 'Papua New Guinea', 'Papua New Guinean kina', 'PGK', 'K');
INSERT INTO `currencies` VALUES (165, 'Paraguay', 'Paraguayan guaraní', 'PYG', '₲');
INSERT INTO `currencies` VALUES (166, 'Peru', 'Peruvian Sol', 'PEN', 'S./');
INSERT INTO `currencies` VALUES (167, 'Philippines', 'Philippine peso', 'PHP', '₱');
INSERT INTO `currencies` VALUES (169, 'Poland', NULL, 'PLN', 'zł');
INSERT INTO `currencies` VALUES (172, 'Qatar', 'Qatari riyal', 'QAR', 'ر.ق');
INSERT INTO `currencies` VALUES (174, 'Romania', 'Romanian leu', 'RON', 'ROL');
INSERT INTO `currencies` VALUES (175, 'Russia', 'Russian ruble', 'RUB', 'RUруб');
INSERT INTO `currencies` VALUES (176, 'Rwanda', 'Rwandan franc', 'RWF', 'RF');
INSERT INTO `currencies` VALUES (177, 'St Helena', 'Saint Helena pound', 'SHP', 'SH£');
INSERT INTO `currencies` VALUES (182, 'Samoa', 'Samoan tala', 'WST', 'WS$');
INSERT INTO `currencies` VALUES (185, 'Sao Tome & Principe', 'São Tomé and Príncipe dobra', 'STD', 'Db');
INSERT INTO `currencies` VALUES (186, 'Saudi Arabia', 'Saudi riyal', 'SAR', 'ر.س');
INSERT INTO `currencies` VALUES (188, 'Serbia', 'Serbian dinar', 'RSD', 'дин');
INSERT INTO `currencies` VALUES (189, 'Seychelles', 'Seychelles rupee', 'SCR', 'SRe');
INSERT INTO `currencies` VALUES (190, 'Sierra Leone', 'Sierra Leonean leone', 'SLL', 'Le');
INSERT INTO `currencies` VALUES (191, 'Singapore', 'Singapore dollar', 'SGD', 'S$');
INSERT INTO `currencies` VALUES (192, 'Slovakia', 'Slovak koruna', 'SKK', 'Sk');
INSERT INTO `currencies` VALUES (194, 'Solomon Islands', 'Solomon Islands dollar', 'SBD', 'SI$');
INSERT INTO `currencies` VALUES (195, 'Somalia', 'Somali shilling', 'SOS', 'Sh');
INSERT INTO `currencies` VALUES (196, 'South Africa', 'South African rand', 'ZAR', 'SAR');
INSERT INTO `currencies` VALUES (199, 'Sri Lanka', 'Sri Lankan rupee', 'LKR', 'LK₨');
INSERT INTO `currencies` VALUES (200, 'Sudan', 'Sudanese dinar', 'SDD', '£Sd');
INSERT INTO `currencies` VALUES (201, 'Suriname', 'Surinamese dollar', 'SRD', 'SR$');
INSERT INTO `currencies` VALUES (203, 'Swaziland', 'Swazi lilangeni', 'SZL', 'SZL');
INSERT INTO `currencies` VALUES (204, 'Sweden', 'Swedish krona/kronor', 'SEK', 'kr');
INSERT INTO `currencies` VALUES (205, 'Switzerland', 'Swiss franc', 'CHF', 'CHF');
INSERT INTO `currencies` VALUES (206, 'Syria', 'Syrian pound', 'SYP', 'S£');
INSERT INTO `currencies` VALUES (207, 'Taiwan', 'New Taiwan dollar', 'TWD', 'NT$');
INSERT INTO `currencies` VALUES (208, 'Tajikistan', 'Tajikistani somoni', 'TJS', 'TJS');
INSERT INTO `currencies` VALUES (209, 'Tanzania', 'Tanzanian shilling', 'TZS', 'TSh');
INSERT INTO `currencies` VALUES (210, 'Thailand', 'Thai baht', 'THB', '฿');
INSERT INTO `currencies` VALUES (214, 'Tonga', NULL, 'TOP', 'PT$');
INSERT INTO `currencies` VALUES (215, 'Trinidad & Tobago', 'Trinidad and Tobago dollar', 'TTD', 'TT$');
INSERT INTO `currencies` VALUES (216, 'Tunisia', 'Tunisian dinar', 'TND', 'د.ت');
INSERT INTO `currencies` VALUES (217, 'Turkey', 'Turkish lira', 'TRY', 'YTL');
INSERT INTO `currencies` VALUES (218, 'Turkmenistan', 'Turkmenistani manat', 'TMM', 'm');
INSERT INTO `currencies` VALUES (221, 'Uganda', 'Ugandan shilling', 'UGX', 'USh');
INSERT INTO `currencies` VALUES (222, 'Ukraine', 'Ukrainian hryvnia', 'UAH', '₴');
INSERT INTO `currencies` VALUES (223, 'United Arab Emirates', 'United Arab Emirates dirham', 'AED', 'د.إ');
INSERT INTO `currencies` VALUES (224, 'UK', 'Pound sterling', 'GBP', 'UK£');
INSERT INTO `currencies` VALUES (225, 'USA', 'United States dollar', 'USD', 'US$');
INSERT INTO `currencies` VALUES (226, 'Uruguay', 'Uruguayan peso', 'UYU', 'UR$');
INSERT INTO `currencies` VALUES (227, 'Uzbekistan', 'Uzbekistan som', 'UZS', 'UZS');
INSERT INTO `currencies` VALUES (228, 'Vanuatu', 'Vanuatu vatu', 'VUV', 'Vt');
INSERT INTO `currencies` VALUES (230, 'Venezuela', 'Venezuelan bolívar', 'VEB', 'Bs');
INSERT INTO `currencies` VALUES (231, 'Vietnam', 'Vietnamese dong', 'VND', '₫');
INSERT INTO `currencies` VALUES (235, 'Yemen', 'Yemeni rial', 'YER', 'YER');
INSERT INTO `currencies` VALUES (236, 'Zambia', 'Zambian kwacha', 'ZMW', 'ZK');
INSERT INTO `currencies` VALUES (237, 'Zimbabwe', 'Zimbabwean dollar A/06', 'ZWD', 'ZWD');
INSERT INTO `currencies` VALUES (239, 'South Sudan', 'South Sudanese pound', 'SSP', 'SSP');
INSERT INTO `currencies` VALUES (240, 'Congo', 'Congolese franc', 'CDF', 'CDF');
