INSERT INTO `languages` VALUES (1, 'Afar', 'aa');
INSERT INTO `languages` VALUES (2, 'Abkhaz', 'ab');
INSERT INTO `languages` VALUES (3, 'Avestan', 'ae');
INSERT INTO `languages` VALUES (4, 'Afrikaans', 'af');
INSERT INTO `languages` VALUES (5, 'Akan', 'ak');
INSERT INTO `languages` VALUES (6, 'Amharic', 'am');
INSERT INTO `languages` VALUES (7, 'Aragonese', 'an');
INSERT INTO `languages` VALUES (8, 'Arabic', 'ar');
INSERT INTO `languages` VALUES (9, 'Assamese', 'as');
INSERT INTO `languages` VALUES (10, 'Avaric', 'av');
INSERT INTO `languages` VALUES (11, 'Aymara', 'ay');
INSERT INTO `languages` VALUES (12, 'Azerbaijani', 'az');
INSERT INTO `languages` VALUES (13, 'South Azerbaijani', 'az');
INSERT INTO `languages` VALUES (14, 'Bashkir', 'ba');
INSERT INTO `languages` VALUES (15, 'Belarusian', 'be');
INSERT INTO `languages` VALUES (16, 'Bulgarian', 'bg');
INSERT INTO `languages` VALUES (17, 'Bihari', 'bh');
INSERT INTO `languages` VALUES (18, 'Bislama', 'bi');
INSERT INTO `languages` VALUES (19, 'Bambara', 'bm');
INSERT INTO `languages` VALUES (20, 'Bengali; Bangla', 'bn');
INSERT INTO `languages` VALUES (21, 'Tibetan Standard, Tibetan, Central ', 'bo');
INSERT INTO `languages` VALUES (22, 'Breton', 'br');
INSERT INTO `languages` VALUES (23, 'Bosnian', 'bs');
INSERT INTO `languages` VALUES (24, 'Catalan; Valencian', 'ca');
INSERT INTO `languages` VALUES (25, 'Chechen', 'ce');
INSERT INTO `languages` VALUES (26, 'Chamorro', 'ch');
INSERT INTO `languages` VALUES (27, 'Corsican', 'co');
INSERT INTO `languages` VALUES (28, 'Cree', 'cr');
INSERT INTO `languages` VALUES (29, 'Czech', 'cs');
INSERT INTO `languages` VALUES (30, 'Old Church Slavonic, Church Slavonic, Old Bulgarian ', 'cu');
INSERT INTO `languages` VALUES (31, 'Chuvash', 'cv');
INSERT INTO `languages` VALUES (32, 'Welsh', 'cy');
INSERT INTO `languages` VALUES (33, 'Danish', 'da');
INSERT INTO `languages` VALUES (34, 'German', 'de');
INSERT INTO `languages` VALUES (35, 'Divehi; Dhivehi; Maldivian;', 'dv');
INSERT INTO `languages` VALUES (36, 'Dzongkha', 'dz');
INSERT INTO `languages` VALUES (37, 'Ewe', 'ee');
INSERT INTO `languages` VALUES (38, 'Greek, Modern ', 'el');
INSERT INTO `languages` VALUES (39, 'English', 'en');
INSERT INTO `languages` VALUES (40, 'Esperanto', 'eo');
INSERT INTO `languages` VALUES (41, 'Spanish; Castilian', 'es');
INSERT INTO `languages` VALUES (42, 'Estonian', 'et');
INSERT INTO `languages` VALUES (43, 'Basque', 'eu');
INSERT INTO `languages` VALUES (44, 'Persian (Farsi)', 'fa');
INSERT INTO `languages` VALUES (45, 'Fula; Fulah; Pulaar; Pular', 'ff');
INSERT INTO `languages` VALUES (46, 'Finnish', 'fi');
INSERT INTO `languages` VALUES (47, 'Fijian', 'fj');
INSERT INTO `languages` VALUES (48, 'Faroese', 'fo');
INSERT INTO `languages` VALUES (49, 'French', 'fr');
INSERT INTO `languages` VALUES (50, 'Western Frisian', 'fy');
INSERT INTO `languages` VALUES (51, 'Irish', 'ga');
INSERT INTO `languages` VALUES (52, 'Scottish Gaelic; Gaelic', 'gd');
INSERT INTO `languages` VALUES (53, 'Galician', 'gl');
INSERT INTO `languages` VALUES (54, 'Guaraní', 'gn');
INSERT INTO `languages` VALUES (55, 'Gujarati', 'gu');
INSERT INTO `languages` VALUES (56, 'Manx', 'gv');
INSERT INTO `languages` VALUES (57, 'Hausa', 'ha');
INSERT INTO `languages` VALUES (58, 'Hebrew (modern)', 'he');
INSERT INTO `languages` VALUES (59, 'Hindi', 'hi');
INSERT INTO `languages` VALUES (60, 'Hiri Motu', 'ho');
INSERT INTO `languages` VALUES (61, 'Croatian', 'hr');
INSERT INTO `languages` VALUES (62, 'Haitian; Haitian Creole', 'ht');
INSERT INTO `languages` VALUES (63, 'Hungarian', 'hu');
INSERT INTO `languages` VALUES (64, 'Armenian', 'hy');
INSERT INTO `languages` VALUES (65, 'Herero', 'hz');
INSERT INTO `languages` VALUES (66, 'Interlingua', 'ia');
INSERT INTO `languages` VALUES (67, 'Indonesian', 'id');
INSERT INTO `languages` VALUES (68, 'Interlingue', 'ie');
INSERT INTO `languages` VALUES (69, 'Igbo', 'ig');
INSERT INTO `languages` VALUES (70, 'Nuosu', 'ii');
INSERT INTO `languages` VALUES (71, 'Inupiaq', 'ik');
INSERT INTO `languages` VALUES (72, 'Ido', 'io');
INSERT INTO `languages` VALUES (73, 'Icelandic', 'is');
INSERT INTO `languages` VALUES (74, 'Italian', 'it');
INSERT INTO `languages` VALUES (75, 'Inuktitut', 'iu');
INSERT INTO `languages` VALUES (76, 'Japanese', 'ja');
INSERT INTO `languages` VALUES (77, 'Javanese', 'jv');
INSERT INTO `languages` VALUES (78, 'Georgian', 'ka');
INSERT INTO `languages` VALUES (79, 'Kongo', 'kg');
INSERT INTO `languages` VALUES (80, 'Kikuyu, Gikuyu ', 'ki');
INSERT INTO `languages` VALUES (81, 'Kwanyama, Kuanyama ', 'kj');
INSERT INTO `languages` VALUES (82, 'Kazakh', 'kk');
INSERT INTO `languages` VALUES (83, 'Kalaallisut, Greenlandic ', 'kl');
INSERT INTO `languages` VALUES (84, 'Khmer', 'km');
INSERT INTO `languages` VALUES (85, 'Kannada', 'kn');
INSERT INTO `languages` VALUES (86, 'Korean', 'ko');
INSERT INTO `languages` VALUES (87, 'Kanuri', 'kr');
INSERT INTO `languages` VALUES (88, 'Kashmiri', 'ks');
INSERT INTO `languages` VALUES (89, 'Kurdish', 'ku');
INSERT INTO `languages` VALUES (90, 'Komi', 'kv');
INSERT INTO `languages` VALUES (91, 'Cornish', 'kw');
INSERT INTO `languages` VALUES (92, 'Kyrgyz', 'ky');
INSERT INTO `languages` VALUES (93, 'Latin', 'la');
INSERT INTO `languages` VALUES (94, 'Luxembourgish, Letzeburgesch ', 'lb');
INSERT INTO `languages` VALUES (95, 'Ganda', 'lg');
INSERT INTO `languages` VALUES (96, 'Limburgish, Limburgan, Limburger ', 'li');
INSERT INTO `languages` VALUES (97, 'Lingala', 'ln');
INSERT INTO `languages` VALUES (98, 'Lao', 'lo');
INSERT INTO `languages` VALUES (99, 'Lithuanian', 'lt');
INSERT INTO `languages` VALUES (100, 'Luba-Katanga', 'lu');
INSERT INTO `languages` VALUES (101, 'Latvian', 'lv');
INSERT INTO `languages` VALUES (102, 'Malagasy', 'mg');
INSERT INTO `languages` VALUES (103, 'Marshallese', 'mh');
INSERT INTO `languages` VALUES (104, 'Macedonian', 'mk');
INSERT INTO `languages` VALUES (105, 'Malayalam', 'ml');
INSERT INTO `languages` VALUES (106, 'Mongolian', 'mn');
INSERT INTO `languages` VALUES (107, 'Malay', 'ms');
INSERT INTO `languages` VALUES (108, 'Maltese', 'mt');
INSERT INTO `languages` VALUES (109, 'Burmese', 'my');
INSERT INTO `languages` VALUES (110, 'Nauru', 'na');
INSERT INTO `languages` VALUES (111, 'Norwegian Bokmål', 'nb');
INSERT INTO `languages` VALUES (112, 'North Ndebele', 'nd');
INSERT INTO `languages` VALUES (113, 'Nepali', 'ne');
INSERT INTO `languages` VALUES (114, 'Ndonga', 'ng');
INSERT INTO `languages` VALUES (115, 'Dutch', 'nl');
INSERT INTO `languages` VALUES (116, 'Norwegian Nynorsk', 'nn');
INSERT INTO `languages` VALUES (117, 'Norwegian', 'no');
INSERT INTO `languages` VALUES (118, 'South Ndebele', 'nr');
INSERT INTO `languages` VALUES (119, 'Navajo, Navaho ', 'nv');
INSERT INTO `languages` VALUES (120, 'Chichewa; Chewa; Nyanja', 'ny');
INSERT INTO `languages` VALUES (121, 'Occitan', 'oc');
INSERT INTO `languages` VALUES (122, 'Ojibwe, Ojibwa ', 'oj');
INSERT INTO `languages` VALUES (123, 'Oromo', 'om');
INSERT INTO `languages` VALUES (124, 'Oriya', 'or');
INSERT INTO `languages` VALUES (125, 'Ossetian, Ossetic ', 'os');
INSERT INTO `languages` VALUES (126, 'Panjabi, Punjabi ', 'pa');
INSERT INTO `languages` VALUES (127, 'Polish', 'pl');
INSERT INTO `languages` VALUES (128, 'Pashto, Pushto ', 'ps');
INSERT INTO `languages` VALUES (129, 'Portuguese', 'pt');
INSERT INTO `languages` VALUES (130, 'Quechua', 'qu');
INSERT INTO `languages` VALUES (131, 'Romansh', 'rm');
INSERT INTO `languages` VALUES (132, 'Kirundi', 'rn');
INSERT INTO `languages` VALUES (133, 'Romanian', 'ro');
INSERT INTO `languages` VALUES (134, 'Russian', 'ru');
INSERT INTO `languages` VALUES (135, 'Kinyarwanda', 'rw');
INSERT INTO `languages` VALUES (136, 'Sardinian', 'sc');
INSERT INTO `languages` VALUES (137, 'Sindhi', 'sd');
INSERT INTO `languages` VALUES (138, 'Northern Sami', 'se');
INSERT INTO `languages` VALUES (139, 'Sango', 'sg');
INSERT INTO `languages` VALUES (140, 'Sinhala, Sinhalese ', 'si');
INSERT INTO `languages` VALUES (141, 'Slovak', 'sk');
INSERT INTO `languages` VALUES (142, 'Slovene', 'sl');
INSERT INTO `languages` VALUES (143, 'Samoan', 'sm');
INSERT INTO `languages` VALUES (144, 'Shona', 'sn');
INSERT INTO `languages` VALUES (145, 'Somali', 'so');
INSERT INTO `languages` VALUES (146, 'Albanian', 'sq');
INSERT INTO `languages` VALUES (147, 'Serbian', 'sr');
INSERT INTO `languages` VALUES (148, 'Swati', 'ss');
INSERT INTO `languages` VALUES (149, 'Southern Sotho', 'st');
INSERT INTO `languages` VALUES (150, 'Sundanese', 'su');
INSERT INTO `languages` VALUES (151, 'Swedish', 'sv');
INSERT INTO `languages` VALUES (152, 'Swahili', 'sw');
INSERT INTO `languages` VALUES (153, 'Tamil', 'ta');
INSERT INTO `languages` VALUES (154, 'Telugu', 'te');
INSERT INTO `languages` VALUES (155, 'Tajik', 'tg');
INSERT INTO `languages` VALUES (156, 'Thai', 'th');
INSERT INTO `languages` VALUES (157, 'Tigrinya', 'ti');
INSERT INTO `languages` VALUES (158, 'Turkmen', 'tk');
INSERT INTO `languages` VALUES (159, 'Tagalog', 'tl');
INSERT INTO `languages` VALUES (160, 'Tswana', 'tn');
INSERT INTO `languages` VALUES (161, 'Tonga (Tonga Islands)', 'to');
INSERT INTO `languages` VALUES (162, 'Turkish', 'tr');
INSERT INTO `languages` VALUES (163, 'Tsonga', 'ts');
INSERT INTO `languages` VALUES (164, 'Tatar', 'tt');
INSERT INTO `languages` VALUES (165, 'Twi', 'tw');
INSERT INTO `languages` VALUES (166, 'Tahitian', 'ty');
INSERT INTO `languages` VALUES (167, 'Uyghur, Uighur ', 'ug');
INSERT INTO `languages` VALUES (168, 'Ukrainian', 'uk');
INSERT INTO `languages` VALUES (169, 'Urdu', 'ur');
INSERT INTO `languages` VALUES (170, 'Uzbek', 'uz');
INSERT INTO `languages` VALUES (171, 'Venda', 've');
INSERT INTO `languages` VALUES (172, 'Vietnamese', 'vi');
INSERT INTO `languages` VALUES (173, 'Volapük', 'vo');
INSERT INTO `languages` VALUES (174, 'Walloon', 'wa');
INSERT INTO `languages` VALUES (175, 'Wolof', 'wo');
INSERT INTO `languages` VALUES (176, 'Xhosa', 'xh');
INSERT INTO `languages` VALUES (177, 'Yiddish', 'yi');
INSERT INTO `languages` VALUES (178, 'Yoruba', 'yo');
INSERT INTO `languages` VALUES (179, 'Zhuang, Chuang ', 'za');
INSERT INTO `languages` VALUES (180, 'Chinese', 'zh');
INSERT INTO `languages` VALUES (181, 'Zulu', '');
